version: "3.9"
services:
  apache-env:
    container_name: apache-env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/apache:/var/www/html
    ports:
      - ${PORT_APACHE}:80
    depends_on:
      - mysql_db

  mysql_db:
    container_name: mysql_db
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - ${PORT_PHP_MY_ADMIN}:80
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - mysql_db
